### ISSUE TITLE
Missing tracking speed option

### ISSUE THREAD

**Issue by KaninchenSpeed** [alvr-org/ALVR#1160]
## Description
The tacking speed option is missing in the settings under the headset category. The setting is there in the current release (v18.2.3).

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[https://linux-hardware.org/?probe=d988a14a82](https://linux-hardware.org/?probe=d988a14a82)

### Installation
**ALVR Version**: v19.0.0-dev00+nightly.2022.08.24

**SteamVR Version**: 1.23.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Pop!_OS 22.04 LTS

**Comment by zarik5** [comment]
Not a bug. This is worked on at the moment. The old tracking options are gone and will be replaced with some sliders in advanced settings
