### ISSUE TITLE
Controller tracking is stopped when doing heavy work in games

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1643]
## Description
HMD tracking works.
However, if the PC experiences a high load, the controller tracking immediately stops and the controller is marked as disconnected.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: Ryzen 7 5800H

**GPU**: Radeon RX 5600M

### Installation
**ALVR Version**: v20.0.0-dev12+nightly.2023.05.09
Please don't tell me it's not nightly up to date.
This's an old bug.

**SteamVR Version**: 1.25.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** : Windows 11

**Comment by Kieaer** [comment]
![Screenshot_20230617-013222_NoMachine](https://github.com/alvr-org/ALVR/assets/44261958/ccbcefb9-665d-4d64-9716-9607ba25c7a4)
graph when there is a problem with controller tracking

**Comment by Kieaer** [comment]
why stale? still has problem in ALVR v20.1.0

**Comment by zarik5** [comment]
Controller tracking works reliably only if you stay below 80ms of total latency. this is a limitation of the Quest runtime, not much we can do.

**Comment by Kieaer** [comment]
![image](https://github.com/alvr-org/ALVR/assets/44261958/78846d65-2daf-479e-a20b-27c15ddcec89)
(Please ignore the last part. occurs when exiting a VR game)
Playing high-performance VR games did not cause controller disconnection.

As a result of several tests, it tracks accurately for 1 second when overload occurs, but disconnects immediately even after 1.1 seconds.
At this time, the Encode delay increases to more than 200ms, but the fps is very stable.

The same problem occurred even with software encoding.
This may not be a performance issue, but a problem in the process of handling controller input in ALVR.

**Comment by Kieaer** [comment]
😟

**Comment by Kieaer** [comment]
😟

**Comment by zarik5** [comment]
I believe this is somewhat fixed
