### ISSUE TITLE
Hand tracking makes mic lose packages 

### ISSUE THREAD

**Issue by alexderpyfox** [alvr-org/ALVR#1826]
## Description
It's on pico 4 So when hand tracking is detected and streamed it makes the mic lose packages so goes really stuttery using 20.2.1
Win 10 
Wifi 6e 

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by zarik5** [comment]
Can you reproduce the same bug on older releases?
