### ISSUE TITLE
Hand tracking is broken on Vision Pro

### ISSUE THREAD

**Issue by Arri-Alexa** [alvr-org/ALVR#2408]
## Description

Since the newest update steam VR doesn't recognize the hand controllers anymore. In VR you can see your hands kind but it doesn't really work. The hands are flickering and lagging. I will upload a video which shows the issue.

Fun fact: If I use the old streamer version 20.10.0 on desktop and 20.11.0 on Vision Pro ist kinda works much better. Don't know what's going on here. But the streamer version 20.11.0 doesn't work for me no matter what I click on the controller page.

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 9 5950x

**GPU**: RTX 3090 Ti

**GPU Driver Version**: Latest

**Audio**:

### Installation
**ALVR Version**: 20.11.0

**ALVR Settings File**:

**SteamVR Version**: Latest

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Arri-Alexa** [comment]
https://github.com/user-attachments/assets/033c4c78-b832-4a27-8e83-9943d3a1b26a

**Comment by Timocop** [comment]
Its broken for everyone ever since the multimodal input commit. The hand tracking root will never be copied over and always stuck at 0,0,0. Seen here:

https://github.com/alvr-org/ALVR/commit/92a5bba96804cf63466acb9daea1ca84b4d920ea#diff-b477b3ffb948ba6466067575cf49d0b8493676812919b4ee58ba2e2a9abc53cbL278

**Comment by metroidmen** [comment]
Same issue here

**Comment by zarik5** [comment]
@shinyquagsire23

**Comment by shinyquagsire23** [comment]
@Arri-Alexa @metroidmen ok having trouble recreating this issue so I need some help,

- What version is the client on? Does the visionOS window show v20.9.1 (app store) or v20.11.0 (testflight)?
- What does the SteamVR status window look like? Is it also flickering? If there's two pairs of controllers (4 total), that means it's using SteamVR input 2.0. One pair is your gamepad controls, and one pair is full skeletal tracking, and it will switch between the two controllers based on gamepad activity with a 5 second hysteresis.
- What is your SteamVR version?
- Are you using gesture-based controls, or a controller/Joy-Con?

**Comment by Arri-Alexa** [comment]
- VisionOS is v20.11.0
- SteamVR Status window is not flickering. Either two or four controllers but either way, they are greyed out, but sometimes blue for a second.
- SteamVR Version is the current one? My steam is updating automatically all the time, so it should be up to date.
- I use joy cons but even if I use my hands it doesn't change anything. It looks like in the video I uploaded.

**Comment by venusyprime** [comment]
Also seeing this with v20.11.0 streamer on Linux.

For me it's inconsistent - the controllers flicker during loading, but in VRChat Home, do not actually present an issue with tracking or gestures.
However, as soon as I join a world with other people, hand tracking stops working correctly, including gestures (apologies for close crop here, didn't turn off nameplates)

https://github.com/user-attachments/assets/daf87635-7fd0-4d77-a120-b96e32c88490

---

Streamer details:

Hardware: https://linux-hardware.org/?probe=bd1e851da7

Assuming the settings file is ~/.config/alvr/session.json:
[session.json](https://github.com/user-attachments/files/17089487/session.json)
[session_old.json](https://github.com/user-attachments/files/17089488/session_old.json) for comparison

(controller emulation type was Index, tried Quest to see if that would make any difference, and no).

The room with my desktop currently isn't wired for Ethernet so I am using the unsupported config of using via a 5GHz connection. Can probably check with actually wiring it in sometime next week

---

Client details:

VisionOS version: 2.0 (22N320) - but was also broken on whatever the last version of 1 was.
ALVR VisonOS version: v20.9.1 (App Store)
SteamVR shows 4 controllers
SteamVR version: 2.7.4
Gesture based controls.

**Comment by gekkehenkie11** [comment]
yeah same here, also on VisionOS 2.0

**Comment by kokashking** [comment]
I experience the same issue. Are there any updates on the topic?
