### ISSUE TITLE
Vive XR Elite controllers are no longer tracking in Steam VR. (Known good ALVR versions broken)

### ISSUE THREAD

**Issue by JohnTator** [alvr-org/ALVR#2409]
## Description
Vive XR Elite controllers are no longer tracked in Steam VR, though hand tracking will move the controllers if enabled. When testing Quest 3, it's controllers track as normal on my ALVR setup. This problem exists on both Linux and Windows.

XR Elite controllers worked perfectly until recently, but now even reverting to known good versions of ALVR (20.7.0) won't work for this headset (Likely triggered by either Steam VR update or Vive Firmware update). Both hands and controller markers are displayed and working in the local environment of the android apk. Head tracking is functioning normally. Using the Vive Streaming hub still functions correctly on Windows (Not an option on Linux). Steam VR shows the controllers as greyed out, with the simulated hand controllers in the newer versions lighting up as tracked. No errors in ALVR output.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: i9-9900KF

**GPU**: GeForce RTX 3080 Ti

**GPU Driver Version**: Nvidia 550.107.02

**Audio**: Pipewire

### Installation
**ALVR Version**:  Tested 20.11.0, 20.10.0, 20.9.0, 20.8.0, 20.7.0, Likely all versions.

**ALVR Settings File**: No settings modified.

**SteamVR Version**: 2.7.4 (also tried previous version option in betas)

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Windows 11, Linux Mint 22 (Ubuntu 24.04)

**Comment by zarik5** [comment]
If a version of ALVR just stopped working and you updated the firmware recently, then wait for a firmware fix

**Comment by zarik5** [comment]
We will investigate. Last time I tried ALVR on a Focus 3 it was working fine

**Comment by Lollerix** [comment]
I'm having the same problem, my controllers are not tracking in steam VR yet i can see the boundaries if i stretch my hands thorough them. Is there any way I could help in diagnose the problem?

**Comment by xytovl** [comment]
I suppose this is related to invalid data in xrLocateHandJointsEXT: https://forum.htc.com/topic/20015-vive-xr-elite-software-10999702-%E2%80%93-release-notes/

**Comment by JohnTator** [comment]
edited title to remove Focus 3 since this appears to be isolated to the XR Elite's firmware as mentioned above.

**Comment by zarik5** [comment]
Ok, so it seems this is unactionable

**Comment by ValkaTR** [comment]
another xr elite user here. the issue is exactly as described by original poster

**Comment by zmerp** [comment]
Oh, thanks for the report. We'll have to tweak the code for the vive. Not sure when i can test this, as i don't have that headset.

**Comment by TsaiTung-Chen** [comment]
Same problem here on VIVE XR Elite.

I've noticed that if I disable the hand tracking from the VIVE XRE settings, the controller moves while I rotate it as shown in the figure below.

![ALVR controller bug](https://github.com/user-attachments/assets/cb65864a-73e0-47f0-b195-220f27e480a5)

There could be something related to the controller changed in a hand tracking update on VIVE XRE.

**Comment by JohnTator** [comment]
Firmware update for the XR Elite on December 6th has fixed this issue for me. Cannot confirm for the Focus Vision, but it had an update on December 5th so it's highly likely the same fix was applied.
