### ISSUE TITLE
ALVR and SteamVR on linux and Meta Quest 3 - Suddenly black screen inside headset

### ISSUE THREAD

**Issue by gabriele2000** [alvr-org/ALVR#2437]
## Description
I'm using a linux-based operating system, Pop_Os to be more precise, version 22.04.
I'm also using their alpha desktop environment, COSMIC, however I feel this isn't what causes my issue.

Long-story short: after cursing in 6 different languages because SteamVR complained about libcef.so missing while it was there and even a blind person could see it, I decided to nuke the whole Steam installation.

Previously I've been using the steam package from ubuntu's repository, this time I decided to download the package directly from the steam website.

Now everything works, after a whole hour of configuring stuff carefully.

However, while SteamVR now works, more of less, and games opens fine, there's a brand new issue: the headset stays black, there is a weird "light" flickering though, and movement is being translated inside games.

Yesterday I could make it work somehow, for 20 minutes, before the connection exploded (it was before the new steam installation, SteamVR somehow started while still complaining about missing libraries, mind you).
Now not even the "virtual world" gets shown inside the headset.

Funny thing: opening SteamVR settings shows a black screen.

The startup option for SteamVR is the following: `WAYLAND_DISPLAY='' QT_QPA_PLATFORM=xcb ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command% --verbose`
"--verbose" was for feeding stuff into an AI to help me, but it spat bullshit about updating drivers and other noobish stuff, so here I am.

Another thing: opening Steam normally then launching SteamVR through ALVR causes SteamVR to close itself after a few seconds.
Starting Steam through ALVR (by clicking "Launch SteamVR") makes it work, but the black settings window and black screen inside the headset remains.

By the way: I start ALVR launcher by using
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json alvr_launcher_linux/ALVR\ Launcher`

No, this isn't the firewall issue, as I always apply the rules after starting ALVR.

I use iptables, not firewalld.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[hw-probe package](https://linux-hardware.org/?probe=ed03e0a42a)

**CPU**: Intel Core i7-7700HQ

**GPU**: iGPU: Intel UHD 630; dGPU: GTX1050TI
(Yes, I'm on a laptop)
**GPU Driver Version**:  iGPU: Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319; dGPU: 560.35.03

**Audio**: Pipewire 1.0.3

### Installation
**ALVR Version**: 20.11.1

**ALVR Settings File**: [session.json](https://github.com/user-attachments/files/17241924/session.json)

**SteamVR Version**: Latest stable version, I believe 2.7
No, the beta version has the same issue, and I won't fiddle with versions again, I lost my mind fixing the issues two days ago, for 6 hours straight.

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
PRETTY_NAME="Pop!_OS 22.04 LTS"

**Comment by gabriele2000** [comment]
Ok, I feel stupid.
The solution is pretty simple:
- Set the firewall rules BEFORE opening Steam
- Open Steam using "Launch SteamVR" and it'll open SteamVR too
- Profit

I also had to reinstall Steam to not have the issue, so maybe it's even that

On top of that, to be sure, if you're using iptables like me, just do a `sudo iptables list` to see if you have the rules set by ALVR

**Comment by gabriele2000** [comment]
Ok, I feel stupid.
The solution is pretty simple:
- Set the firewall rules BEFORE opening Steam
- Open Steam using "Launch SteamVR" and it'll open SteamVR too
- Profit

I also had to reinstall Steam to not have the issue, so maybe it's even that

On top of that, to be sure, if you're using iptables like me, just do a `sudo iptables list` to see if you have the rules set by ALVR
