### ISSUE TITLE
Hand Tracking Terribly Shaky on Vision Pro

### ISSUE THREAD

**Issue by metroidmen** [alvr-org/ALVR#2443]
## Description

Video attached. 

https://github.com/user-attachments/assets/bb41a4df-7ebb-46a6-accf-2a664174cd71

Hands are super jittery and fly all over the place when moving them. Prediction settings seem to make little difference. This has been this way for months so I’m not sure if this is “normal” behavior. It’s never not been this way for me

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:
All versions
**ALVR Settings File**:

**SteamVR Version**:
All versions
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by metroidmen** [comment]
Issue persists

**Comment by zmerp** [comment]
@shinyquagsire23
