### ISSUE TITLE
Timestamp for tracker prediction 

### ISSUE THREAD

**Issue by junlinp** [alvr-org/ALVR#2445]
## Description

https://github.com/alvr-org/ALVR/blob/cf52f875c2720b2c17ef490cfbec4c07ee5f41aa/alvr/client_core/src/lib.rs#L267
tracking_timestamp is a duration instread of a timestamp actually.
the prediction for tracking would have no effect.
is my understood right?
https://github.com/alvr-org/ALVR/blob/cf52f875c2720b2c17ef490cfbec4c07ee5f41aa/alvr/client_core/src/lib.rs#L269

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by The-personified-devil** [comment]
Yea ur right. How tf did I miss that in pr review...

**Comment by zarik5** [comment]
Damn, indeed i tested with hand tracking but no controllers
