### ISSUE TITLE
Hand tracking left hand controls don't work on quest 2, 3, etc.

### ISSUE THREAD

**Issue by Breelandthecat** [alvr-org/ALVR#2553]
## Description
Quick bug report, it's in the title: the right hand controls work, but left hand doesn't. Can you fix this on quest? Can you also add options to configure the controls for hand tracking hand controls, like disabling buttons or changing the gesture you use? Perhaps also gestures for joystick directions. I like to play games with hand tracking that don't support it like rec room. Thank you!

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Arbel-arad** [comment]
i have the same problem.
right hand controls show up as expected, but left hand doesn't work.
thought it might be something with steamVR but resetting didn't change anything.

**Comment by Breelandthecat** [comment]
I Found the issue, You only need to disable SteamVR 2.0 input. but if its enabled there should be a notice for this issue. Its weird.

**Comment by Breelandthecat** [comment]
> i have the same problem. right hand controls show up as expected, but left hand doesn't work. thought it might be something with steamVR but resetting didn't change anything.

The issue was that you need to turn off SteamVR Input 2.0. I Found that, weird.

**Comment by zmerp** [comment]
This should be investigated further

**Comment by chemifox42** [comment]
this is still an issue for me, hands show up and work in vrchat but do not work for steamvr menu, my left controller is broken beyond repair so i kind of need hand tracking to work so i can open the Vr dashboard


> > i have the same problem. right hand controls show up as expected, but left hand doesn't work. thought it might be something with steamVR but resetting didn't change anything.
> 
> The issue was that you need to turn off SteamVR Input 2.0. I Found that, weird.

**Comment by malik05051** [comment]
Where do I disable SteamVR 2.0 input ?

**Comment by chemifox42** [comment]
I was thinking they meant that they switched the bindings to alvr, but now I'm wondering if there's a way to turn steamvr input 3.0 off in steam itself

**Comment by Xlaits** [comment]
I turned off SteamVR2.0 Input, and now both of my controllers have lost their ability to be tracked.
