### ISSUE TITLE
v15 to-do list

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#381]
* [x] Change PlayspaceSync packet perimeter_points from Point3 to Point2
* [x] Move game audio and microphone from the ReservedBuffer in the control socket to a separate stream.
* [x] Add separate variant for keepalive packets
* [x] Add TCP and UDP streams. All network IO should be moved to these streams (QUIC and reliable mode are deferred).
