### ISSUE TITLE
v16 to-do list

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#513]
* [ ] Add field in `ClientConfigPacket` for server version.
* [ ] Replace `ClientControlPacket::Reserved("StreamReady")` with `StreamReady`.
* [ ] Remove version check for sending and receiving `StreamReady`.
