### ISSUE TITLE
NeoVR Hand tracking 

### ISSUE THREAD

**Issue by ColdIce1605** [alvr-org/ALVR#972]
Just NeoVR seems to be affected by this bug.

## Description
The right hand is stuck in the center / below the HMD on the floor of Guardian only seems to have in NeosVR. 
Leave a reaction if this also affects you.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=63d492d4bb

### Installation
**ALVR Version**:
Git

**SteamVR Version**:
1.21.8 beta

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
EndeavourOS

**Comment by BeckersC** [comment]
I can confirm this issue on yesterdays nightly release in NeosVR on windows. Right controller stuck on Floor, does not rotate and the AB Buttons do not respond. Left controller works normal. Steamvr can still track both controllers and all buttons. Issue appears both in Oculus Rift S and Quest 2 controler emulation. I did not try the other modes. 

When I get the time I ll pinpoint the exact nightly since when this issue has appeared.
Issue not present in 17.0 stable release.
